#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${ROOT_DIR:-$(cd -- "${SCRIPT_DIR}/.." && pwd)}"
REPORT_DIR="${REPORT_DIR:-${ROOT_DIR}/artifacts/reports}"
ROADMAP_DIR="${ROADMAP_DIR:-${ROOT_DIR}/docs/roadmap}"
OUTPUT_FILE="${OUTPUT_FILE:-${ROADMAP_DIR}/live-status.md}"

read_status_value() {
  local file_path="$1"
  local key="$2"
  local default_value="${3:-unknown}"

  if [ ! -f "${file_path}" ]; then
    printf '%s\n' "${default_value}"
    return
  fi

  local value
  value="$(grep -E "^${key}=" "${file_path}" | tail -n 1 | cut -d= -f2- || true)"
  if [ -z "${value}" ]; then
    printf '%s\n' "${default_value}"
  else
    printf '%s\n' "${value}"
  fi
}

mkdir -p "${ROADMAP_DIR}"

latest_status_file="${REPORT_DIR}/latest-status.txt"
latest_loop_status_file="${REPORT_DIR}/latest-loop-status.txt"
latest_kernel_svc_diagnostic_status_file="${REPORT_DIR}/latest-bootstrap-kernel-svc-diagnostic-status.txt"
latest_pretransfer_svc_diagnostic_status_file="${REPORT_DIR}/latest-bootstrap-pretransfer-svc-diagnostic-status.txt"
latest_el0_diagnostic_status_file="${REPORT_DIR}/latest-bootstrap-el0-diagnostic-status.txt"
latest_trap_diagnostic_status_file="${REPORT_DIR}/latest-bootstrap-trap-diagnostic-status.txt"
latest_svc_diagnostic_status_file="${REPORT_DIR}/latest-bootstrap-svc-diagnostic-status.txt"

report_generated_at="$(read_status_value "${latest_status_file}" "generated_at_utc")"
report_file="$(read_status_value "${latest_status_file}" "report_file")"
env_status="$(read_status_value "${latest_status_file}" "environment_status")"
validate_status="$(read_status_value "${latest_status_file}" "local_validation_status")"

loop_timestamp="$(read_status_value "${latest_loop_status_file}" "timestamp_utc")"
loop_iteration="$(read_status_value "${latest_loop_status_file}" "iteration")"
loop_log_file="$(read_status_value "${latest_loop_status_file}" "log_file")"
loop_summary_file="$(read_status_value "${latest_loop_status_file}" "summary_file")"
loop_env_status="$(read_status_value "${latest_loop_status_file}" "env_status")"
loop_validate_status="$(read_status_value "${latest_loop_status_file}" "validate_status")"
loop_report_status="$(read_status_value "${latest_loop_status_file}" "report_status")"
kernel_svc_diagnostic_status="$(read_status_value "${latest_kernel_svc_diagnostic_status_file}" "overall_status" "not_run")"
kernel_svc_diagnostic_log="$(read_status_value "${latest_kernel_svc_diagnostic_status_file}" "log_file")"
kernel_svc_caller_capture_matched="$(read_status_value "${latest_kernel_svc_diagnostic_status_file}" "caller_capture_matched" "unknown")"
kernel_svc_caller_capture_mismatch="$(read_status_value "${latest_kernel_svc_diagnostic_status_file}" "caller_capture_mismatch" "unknown")"
pretransfer_svc_diagnostic_status="$(read_status_value "${latest_pretransfer_svc_diagnostic_status_file}" "overall_status" "not_run")"
pretransfer_svc_diagnostic_log="$(read_status_value "${latest_pretransfer_svc_diagnostic_status_file}" "log_file")"
el0_diagnostic_status="$(read_status_value "${latest_el0_diagnostic_status_file}" "overall_status" "not_run")"
el0_diagnostic_log="$(read_status_value "${latest_el0_diagnostic_status_file}" "log_file")"
trap_diagnostic_status="$(read_status_value "${latest_trap_diagnostic_status_file}" "overall_status" "not_run")"
trap_diagnostic_log="$(read_status_value "${latest_trap_diagnostic_status_file}" "log_file")"
svc_diagnostic_status="$(read_status_value "${latest_svc_diagnostic_status_file}" "overall_status" "not_run")"
svc_diagnostic_log="$(read_status_value "${latest_svc_diagnostic_status_file}" "log_file")"

cat > "${OUTPUT_FILE}" <<EOF
# NovaOS Live Status

This file is generated by \`scripts/update-roadmap-status.sh\`.
Open this first when resuming NovaOS from another Codex session.
Report links below point to local runtime artifacts; run \`make report\` if they are absent in a fresh clone.

## Resume Order

1. [START-HERE.md](${ROOT_DIR}/docs/roadmap/START-HERE.md)
2. [master-roadmap-checklist.md](${ROOT_DIR}/docs/roadmap/master-roadmap-checklist.md)
3. [m1-progress-2026-03-30.md](${ROOT_DIR}/docs/roadmap/m1-progress-2026-03-30.md)
4. [latest-report.md](${ROOT_DIR}/artifacts/reports/latest-report.md)

## Active Phase

- active_phase: M0 portability refactor with Spark boot continuity
- repo_root: ${ROOT_DIR}
- latest_report_generated_at_utc: ${report_generated_at}
- latest_loop_timestamp_utc: ${loop_timestamp}
- latest_loop_iteration: ${loop_iteration}

## Durable Baseline

- QEMU Arm64 UEFI still reaches the current Spark lane: \`stage0 post-exit -> stage1 entered -> kernel entered\`
- the live boot chain still uses \`NovaBootInfoV1\`, typed Nova Payload v1 images, digest metadata, and verification metadata as its primary contract, while the loader also keeps an internal/transitional \`BootInfo v2\` sidecar with display/storage/network path facts plus one integrated/UMA accelerator seed that stage1 carries into the raw kernel entry under a dedicated payload ABI and the raw entry resolves into a compact validated v2 bringup summary before current planning continues on v1
- \`libs/nova_fabric\` now defines portable platform, topology, queue, pool, and accelerator-seed contracts
- \`nova_rt\` now carries a Rust mirror of the \`BootInfo v2\` draft alongside the live v1 handoff
- \`services/acceld\` now has backend traits with CPU, GB10, RTX, and Hopper placeholder backends
- \`services/memd\` now has topology-profile traits with UMA, discrete, NVLink, and MIG placeholders
- \`kernel/arch/x86_64\` and \`drivers/bus/pci\` exist as early portability lanes
- \`kernel/arch/arm64\` now carries validated raw bringup state into the shared runtime and emits early boot-console output over QEMU trace plus framebuffer when present
- \`abi/syscall/nova_syscall_v1.h\` and \`nova_rt\` now define the first typed syscall ABI draft, and \`kernel/arch/arm64\` now carries the Arm64 \`svc\` scaffold dispatcher, bound to a concrete current bootstrap task and bounded by bootstrap endpoint/shared-memory quotas, with the installed bootstrap runtime now marking the first reserved bootstrap endpoint and shared-memory lanes ready when the capsule grants them and those lanes returning real kernel-owned results in the QEMU probe
- \`boot/mkimage\` now pads kernel payload images to an alignment-safe \`load_offset\`, so stage1's existing in-place \`load_base\` contract lands the live Arm64 kernel body on a vector-safe address, and the kernel also retains a runtime-aligned exception-vector fallback for narrower diagnostics
- \`init.capsule\` now builds as a typed \`InitCapsule v1\` artifact with an embedded bootstrap service payload body, stage0/stage1 validate it before handoff continues, stage0 snapshots that embedded payload plus populated portable bootstrap user-window and loader-reserved bootstrap frame-arena policies into the transitional \`BootInfo v2\` sidecar, and the raw Arm64 kernel records a compact bootstrap task summary from the capsule header in QEMU, surfaces the current bootstrap task identity, derives a first launch plan from the validated sidecar descriptor, and performs the first in-place bootstrap payload transfer on a dedicated stack with a typed bootstrap context in \`x0\` while hardening the EL1 bootstrap stack-bank setup, logging the current unisolated bootstrap boundary plan plus the isolated \`drop-to-el0\`/\`el0-svc\` target plan, exposing a transitional same-EL bootstrap kernel-call gate through that context, proving a payload-originated same-EL \`svc\` return in the default QEMU smoke lane, splitting the lower-EL AArch64 sync vector onto a lower-EL \`svc\` handler with a default-smoke dry-run for the future EL0 return path, computing ready typed EL0 user-window, user-mapping, backing-frame arena, and page-table descriptor plans plus populating payload/context/stack backing frames, constructing a fixed transitional AArch64 translation-table set, and preparing TTBR/TCR/MAIR values for payload rebase/context/stack placement, and keeping direct payload parsing as the compatibility fallback
- \`kernel/arch/arm64\` now also carries feature-gated \`bootstrap_kernel_svc_probe\`, \`bootstrap_pretransfer_svc_probe\`, and \`bootstrap_el0_probe\` lanes, \`apps/initd\` carries feature-gated \`bootstrap_svc_probe\`, \`bootstrap_trap_probe\`, and \`bootstrap_el0_probe\` lanes, and the dedicated QEMU diagnostic runners capture the current same-EL live exception status plus a raw no-MMU EL1-to-EL0 \`eret\` probe that reaches the lower-EL \`svc\` handler and returns to EL0 spin without weakening the default QEMU smoke baseline
- \`BootInfo v2\` exists as the portable-fabric draft contract, and the loader now plans around v2 seeds internally while the raw live kernel entry accepts an optional v2 sidecar, resolves it into a compact validated bringup summary, and current bringup still derives primary state from v1
- \`spark-observe\` now emits a persisted structured report with display/storage/network seed paths and a transitional Spark accelerator-seed draft
- \`novaaa64\` now emits a persisted structured loader handoff report with BootInfo v2 and payload-readiness facts before the live handoff exits boot services
- \`scripts/compare-spark-observe-reports.sh\` now compares a real Spark observatory report against the persisted QEMU baseline and writes a stable comparison artifact
- \`scripts/prepare-spark-hardware-bundle.sh\` now stages manual observatory and loader bundles under \`artifacts/hardware/\`
- \`scripts/install-spark-hardware-bundle.sh\` now copies those staged bundles onto a mounted ESP, can optionally schedule \`BootNext\`, and keeps a stable install record
- \`scripts/collect-spark-observe-report.sh\` now ingests a returned Spark observatory report from the ESP or an explicit path and runs the baseline comparison flow
- \`scripts/collect-novaaa64-loader-report.sh\` now ingests a returned Spark loader handoff report from the ESP or an explicit path and validates it against the QEMU baseline
- \`scripts/check-spark-stage-chain-proof.sh\` now validates returned stage0 -> stage1 -> kernel evidence against the current QEMU markers
- \`scripts/finalize-spark-hardware-proof.sh\` now writes one combined Spark hardware-proof summary from the returned observatory report, loader handoff report, and validated stage-chain evidence
- \`scripts/complete-spark-hardware-proof.sh\` now wraps the full post-boot return path by collecting both reports, validating the stage-chain markers, and publishing the combined hardware-proof summary in one command

## Current Gaps

- the current raw kernel bringup still derives primary state from \`NovaBootInfoV1\` even though the live handoff now carries an optional \`BootInfo v2\` sidecar that is resolved into a compact validated bringup summary
- the typed \`init.capsule\` path now enforces a narrow task-bound bootstrap policy, carries validated bootstrap payload, populated portable bootstrap user-window, and loader-reserved bootstrap frame-arena descriptors through \`BootInfo v2\`, and now hands the payload a typed bootstrap context in \`x0\` that also supports a transitional same-EL bootstrap kernel-call round-trip, but the default transfer still runs in-place under the raw-kernel environment rather than as a real isolated \`initd\` task, and the current QEMU lane still only proves \`current_el=1\` with an explicitly logged unisolated \`current-el-svc\` current boundary plan plus a logged isolated \`drop-to-el0\`/\`el0-svc\` target boundary plan. The same-EL exception defect is now cleared in QEMU: the default smoke lane now proves payload-originated \`svc\` return, the lower-EL AArch64 vector path now has the correct ELR-advance handler proven by a kernel-owned dry-run, the feature-gated EL0 diagnostic now proves raw no-MMU \`eret\` to EL0 and lower-EL \`svc\` return to EL0 spin, and the kernel now has tested EL0 mapping-readiness, backing-frame arena, page-table descriptor planners, payload/context/stack backing-frame population, transitional AArch64 translation-table construction, and TTBR/TCR/MAIR register planning that rebase the embedded payload into the proposed user image window, with QEMU proving all three descriptor stages plus backing-frame population, table construction, and register preparation as ready. The kernel-owned \`svc\`, pre-transfer \`svc\`, payload-originated \`svc\`, and payload-originated \`brk\` diagnostics all return end-to-end, with the kernel-owned \`svc\` scalar caller capture matching \`x0/status\`, \`x1/value0\`, and \`x2/value1\`. Full capability objects, broader endpoint routing, shared-memory policy beyond the first reserved bootstrap region, kernel-owned allocator integration, controlled TTBR/TCR/MAIR installation, MMU activation, real user mappings/stacks for the EL0 boundary, and a true isolated \`initd\` task still remain ahead
- the persisted observatory report still needs real Spark capture and comparison against the QEMU baseline
- real Spark hardware acceptance is still missing for the observatory, loader, and kernel milestones because the actual operator/root/reboot flow still has to happen on hardware, and the loader milestone still needs both the returned handoff report and stage0 -> stage1 -> kernel evidence from hardware
- x86_64, PCI, RTX, and Hopper lanes are placeholders only; no second hardware lane boots yet
- timer, IRQ, topology, capability, endpoint routing beyond the first reserved bootstrap slot, shared-memory policy beyond the first reserved bootstrap region, a real EL0 syscall boundary, storage, shell, update, CPU inference, topology-aware \`memd\`, and native accelerator work are still ahead

## Latest Automation Status

- environment_status: ${env_status}
- local_validation_status: ${validate_status}
- loop_env_status: ${loop_env_status}
- loop_validate_status: ${loop_validate_status}
- loop_report_status: ${loop_report_status}
- bootstrap_kernel_svc_diagnostic_status: ${kernel_svc_diagnostic_status}
- bootstrap_kernel_svc_caller_capture_matched: ${kernel_svc_caller_capture_matched}
- bootstrap_kernel_svc_caller_capture_mismatch: ${kernel_svc_caller_capture_mismatch}
- bootstrap_pretransfer_svc_diagnostic_status: ${pretransfer_svc_diagnostic_status}
- bootstrap_el0_diagnostic_status: ${el0_diagnostic_status}
- bootstrap_svc_diagnostic_status: ${svc_diagnostic_status}
- bootstrap_trap_diagnostic_status: ${trap_diagnostic_status}
- latest_report: ${report_file}
- latest_loop_log: ${loop_log_file}
- latest_loop_summary: ${loop_summary_file}
- latest_bootstrap_kernel_svc_diagnostic_log: ${kernel_svc_diagnostic_log}
- latest_bootstrap_pretransfer_svc_diagnostic_log: ${pretransfer_svc_diagnostic_log}
- latest_bootstrap_el0_diagnostic_log: ${el0_diagnostic_log}
- latest_bootstrap_svc_diagnostic_log: ${svc_diagnostic_log}
- latest_bootstrap_trap_diagnostic_log: ${trap_diagnostic_log}
- latest_report_link: ${ROOT_DIR}/artifacts/reports/latest-report.md
- latest_status_link: ${ROOT_DIR}/artifacts/reports/latest-status.txt
- latest_loop_status_link: ${ROOT_DIR}/artifacts/reports/latest-loop-status.txt

## Resume Commands

\`\`\`bash
cd ${ROOT_DIR}
systemctl --user status novaos-validation.service --no-pager
tail -n 40 ${ROOT_DIR}/artifacts/reports/latest-status.txt
tail -n 40 ${ROOT_DIR}/artifacts/reports/latest-loop-status.txt
sed -n '1,260p' ${ROOT_DIR}/docs/roadmap/master-roadmap-checklist.md
sed -n '1,260p' ${ROOT_DIR}/docs/roadmap/live-status.md
sed -n '1,220p' ${ROOT_DIR}/docs/roadmap/m1-progress-2026-03-30.md
./ci/validate-local.sh
\`\`\`

## Current Execution Queue

- keep the Spark boot chain green while the portable-fabric contracts harden
- use \`scripts/prepare-spark-hardware-bundle.sh\` and \`scripts/install-spark-hardware-bundle.sh\` as the supported staging/install path for real Spark proof
- bring back a real Spark observatory report, a real Spark \`novaaa64\` loader handoff report, and stage0 -> stage1 \`BootInfo v2\` sidecar evidence, then prefer \`scripts/complete-spark-hardware-proof.sh\` to validate and finalize the full proof set while current kernel bringup still uses \`BootInfo v1\` as its primary contract
- validate the new portability scaffolding in the 24/7 loop and keep the checklist current for handoff
EOF
